config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    invitations: 'users/invitations',
  }

  namespace :app do
    get 'dashboard' => 'dashboards#index',  as: :dashboards
    get 'setting' => 'settings#index',  as: :settings
    get 'report' => 'reports#index',  as: :reports
    resources :users do
      collection do
        get :profile
      end
    end
  end

  namespace :admin do
    get 'dashboard' => 'dashboards#index',  as: :dashboards
    get 'setting' => 'settings#index',  as: :settings
    get 'report' => 'reports#index',  as: :reports
    resources :users
    resources :businesses, only: [:update] do
      collection do
        get :profile
      end
    end
  end
end

app/controllers/app/settings_controller.rb
class App::SettingsController < App::BaseController

  def index
  end

end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/app/settings/index.html.erb
<section class="content-header">
  <h1>
    Settings
  </h1>
</section>
<section class="content">
  <div class="row">
    <div class="col-md-6">
      <div class="box">
        <div class="box-header">
        <h3 class="box-title"> Users</h3>
        </div>
        <div class="box-body">
          <ul>
            <li><a href="<%= admin_users_path %>">All users</a></li>
            <li> <a href="<%= profile_app_users_path %>">Current user profile</a> </li>
            <li><a href="<%= profile_admin_businesses_path %>">Business profile</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>